/*  =========================================================================
    sph_stock - class description

    Copyright (c) 2020 the Contributors as noted in the AUTHORS file.

    This file is part of Sphactor, an open-source framework for high level
    actor model concurrency --- http://sphactor.org

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

#ifndef SPH_STOCK_H_INCLUDED
#define SPH_STOCK_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/sph_stock.api" to make changes.
//  @interface
//  This is a stable class, and may not change except for emergencies. It
//  is provided in stable builds.
//
SPHACTOR_EXPORT void
    sph_stock_register_all (void);

//  Simple actor that logs received messages to stdout
SPHACTOR_EXPORT zmsg_t *
    sph_stock_log_actor (sphactor_event_t *event, void *args);

//  Simple actor that counts received messages
SPHACTOR_EXPORT zmsg_t *
    sph_stock_count_actor (sphactor_event_t *event, void *args);

//  Simple actor that send a periodic message
SPHACTOR_EXPORT zmsg_t *
    sph_stock_pulse_actor (sphactor_event_t *event, void *args);

//  Self test of this class.
SPHACTOR_EXPORT void
    sph_stock_test (bool verbose);

//  @end

#ifdef __cplusplus
}
#endif

#endif
