/*  =========================================================================
    sphactor_classes - private header file

    Copyright (c) the Contributors as noted in the AUTHORS file.

    This file is part of Sphactor, an open-source framework for high level
    actor model concurrency --- http://sphactor.org

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef SPHACTOR_CLASSES_H_INCLUDED
#define SPHACTOR_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/libsphactor.h"

//  Opaque class structures to allow forward references

//  Extra headers

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef SPHACTOR_BUILD_DRAFT_API

//  Self test for private classes
SPHACTOR_PRIVATE void
    sphactor_private_selftest (bool verbose, const char *subtest);

#endif // SPHACTOR_BUILD_DRAFT_API

#endif
