/*  =========================================================================
    sphactor_shim - class description

    Copyright (c) the Contributors as noted in the AUTHORS file.

    This file is part of Zyre, an open-source framework for proximity-based
    peer-to-peer applications -- See http://zyre.org.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.
    =========================================================================
*/

/*
@header
    sphactor_shim -
@discuss
@end
*/

#include "sphactor_classes.h"

//  Structure of our class

struct _sphactor_shim_t {
    sphactor_shim_handler_fn *handler;  // our handler
    void* args;     // arguments for the handler
    zuuid_t *uuid;  // our identifier (NULL if generated by sphactor_node
    char *name;     // our human readable name
    sphactor_node_t *parent; //  the sphactor_node who's carrying us
    bool verbose;
};


//  --------------------------------------------------------------------------
//  Create a new sphactor_shim

sphactor_shim_t *
sphactor_shim_new (void)
{
    sphactor_shim_t *self = (sphactor_shim_t *) zmalloc (sizeof (sphactor_shim_t));
    assert (self);
    //  Initialize class properties here
    self->args = NULL;
    self->uuid = zuuid_new();
    self->name = "TEMP";
    self->verbose = true;
    return self;
}


//  --------------------------------------------------------------------------
//  Destroy the sphactor_shim

void
sphactor_shim_destroy (sphactor_shim_t **self_p)
{
    assert (self_p);
    if (*self_p) {
        sphactor_shim_t *self = *self_p;
        //  Free class properties here
        zuuid_destroy(&self->uuid);
        //  Free object itself
        free (self);
        *self_p = NULL;
    }
}

int
sphactor_shim_handler (sphactor_shim_t *self, sphactor_shim_handler_fn handler, void *arg)
{
    assert(self);
    self->handler = handler;
    self->args = arg;
}

zmsg_t *
sphactor_shim_handle(sphactor_shim_t *self, zmsg_t *msg)
{
    assert( self );
    self->handler(self, msg, self->args);
}
//  --------------------------------------------------------------------------
//  Self test of this class

// If your selftest reads SCMed fixture data, please keep it in
// src/selftest-ro; if your test creates filesystem objects, please
// do so under src/selftest-rw.
// The following pattern is suggested for C selftest code:
//    char *filename = NULL;
//    filename = zsys_sprintf ("%s/%s", SELFTEST_DIR_RO, "mytemplate.file");
//    assert (filename);
//    ... use the "filename" for I/O ...
//    zstr_free (&filename);
// This way the same "filename" variable can be reused for many subtests.
#define SELFTEST_DIR_RO "src/selftest-ro"
#define SELFTEST_DIR_RW "src/selftest-rw"

void
sphactor_shim_test (bool verbose)
{
    printf (" * sphactor_shim: ");

    //  @selftest
    //  Simple create/destroy test
    sphactor_shim_t *self = sphactor_shim_new ();
    assert (self);
    assert (strlen (zuuid_str (self->uuid)) == ZUUID_STR_LEN);
    sphactor_shim_destroy (&self);
    //  @end
    printf ("OK\n");
}
