name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: libZMQ Dep
      run: |
        git clone https://github.com/zeromq/libzmq.git
        cd libzmq
        ./autogen.sh
        ./configure
        make
        sudo make install
    - name: CZMQ Dep
      run: |
        git clone https://github.com/zeromq/czmq.git
        cd czmq
        ./autogen.sh
        ./configure
        make
        sudo make install
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
