name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
#          - platform: x64
#            configuration: release
#            os: windows-2019
#            CMAKE_GENERATOR: Visual Studio 16 2019
#            MSVCVERSION: v142
#            MSVCYEAR: vs2019

    steps:
    - uses: actions/checkout@v2

    - name: Add brew packages
      if: matrix.os == 'macos-latest'
      shell: bash
      run: brew install automake autoconf cmake

    - name: libZMQ Dep
      if: matrix.os != 'windows-2019' 
      run: |
        git clone https://github.com/zeromq/libzmq.git
        cd libzmq
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: CZMQ Dep
      if: matrix.os != 'windows-2019'
      run: |
        git clone https://github.com/zeromq/czmq.git
        cd czmq
        ./autogen.sh
        ./configure
        make
        sudo make install

    - name: ldconfig
      if: matrix.os == 'ubuntu-latest'
      run: sudo ldconfig

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C Debug -VV
